### ISSUE TITLE
Writing the MilkPOWDER with SDDP

### ISSUE THREAD

**Issue by hghayoom** [odow/MilkPOWDER#1]
Hi Odow, 
I have read your paper "A multi-stage stochastic optimization model of a pastoral dairy farm" and the codes for "MilkPOWDER".It is almost a good and comprehensive example.  In that version, you have used some definations like "expressions", "rhsnoises". I am wondering if they are used because you had not improved SDDP? If you want to rewrite it now, do you write it the same way ar you will change. 
Thanks for your amazing Tool.

**Comment by odow** [comment]
You can find a more recent version of the paper: https://github.com/odow/SDDP.jl/blob/master/papers/policy_graph/paper.jl

This repo uses an old version of SDDP.jl.

**Comment by hghayoom** [comment]
Odow, You are amazing. 
🙏 Thanks

**Comment by odow** [comment]
I'm going to close this issue and archive the repository. Please open an issue at https://github.com/odow/SDDP.jl/issues if you have any follow-up questions.
